# Generated by Django 5.2.1 on 2025-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('parking', 'Parking'), ('ride', 'Ride')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peak_multiplier', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
